### ISSUE TITLE
Fix Cargo.toml not building

### ISSUE THREAD

**Issue by dbkblk** [dividebysandwich/LightningView#12]
Hi,

In place, the project cannot be build because imagepipe and rawler are local dependencies in Cargo.toml.
```
[dependencies.imagepipe]
version = "0.5.0"
path = "../imagepipe"
[dependencies.rawler]
version = "0.6.0"
path = "../dnglab/rawler"
```

It should be fixed with:
```
rawler = "0.6.0"
imagepipe = "0.5.0"
```

**Comment by dividebysandwich** [comment]
The problem with that is that I fixed several problems with color processing and exif handling in rawler and imagepipe, and you will lose that if you use the official crates. This will break viewing of many raw formats, like most Fuji and Sony camers for example.

**Comment by dbkblk** [comment]
Ok, thank you for your answer.
I didn't planned to use the software, just to review the code for another project, but I wanted to let you know about the issue :)

**Comment by dividebysandwich** [comment]
I don't have a good way forward though - I can't have them merge this upstream because I don't know how it will impact dnglab. I guess rawler should be extracted into its own repo at some point. Also note that I use imagepipe to replace some of rawler / dnglab's functions in the image processing chain because imagepipe is orders of magnitude faster due to more efficient use of memory. Hence I decided that for LightningView, I could live with a local branch, and I simply merge in any upstream updates as they happen.

**Comment by dividebysandwich** [comment]
Closing this for now because I don't think a solution is forthcoming. I strongly recommend building with my branches locally checked out alongside lightningview.

**Comment by quantenzitrone** [comment]
instead of depending on local paths you should point the Cargo.toml to online repositories of your forks
